export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const USER_SESSION = "USER_SESSION";

export const GET_USERPRODUCT_SUCCESS = "GET_USERPRODUCT_SUCCESS";
export const GET_USERPRODUCT_FAILURE = "GET_USERPRODUCT_FAILURE";

export const GET_SELLPRODUCT_SUCCESS = "GET_SELLPRODUCT_SUCCESS";
export const GET_SELLPRODUCT_FAILURE = "GET_SELLPRODUCT_FAILURE";

export const GET_USERDATA = "GET_USERDATA";
export const USER_EDIT = "USER_EDIT";

export const USER_DP = "USER_DP";
export const UPDATE_NUMBER = "UPDATE_NUMBER";
export const UPDATE_CITY = "UPDATE_CITY";

export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const GET_FAV_ITEMS = "GET_FAV_ITEMS";
export const GET_ORDER_ITEMS = "GET_ORDER_ITEMS";

export const GET_CATEGORYDATA = "GET_CATEGORYDATA";
