export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const USER_SESSION = "USER_SESSION";

export const GET_USERPRODUCT_SUCCESS = "GET_USERPRODUCT_SUCCESS";
export const GET_USERPRODUCT_FAILURE = "GET_USERPRODUCT_FAILURE";

export const USER_EDIT = "USER_EDIT";
